//------------------------------------------------------------------------------ 
// <auto-generated> 
//     This code was generated by the AssemblyInfoVersion.bat script 
// 
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------ 
 
using System.Reflection; 
 
[assembly: AssemblyVersion("1.5.0.0")] 
[assembly: AssemblyFileVersion("1.5.0.0")] 
[assembly: AssemblyInformationalVersion("1.5.0")] 
 
